apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: campus-navi

data:
  AWS_REGION: "ap-northeast-2"
  S3_BUCKET: "campus-navi-bucket"
  S3_REGION: "ap-northeast-2"
  S3_BASE_URL: "https://campus-navi.com"
  CORS_ALLOWED_ORIGINS: "https://campus-navi.com,https://www.campus-navi.com"
  AI_SERVER_URL: "http://ai-service:8000"