apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ai-secret
  namespace: campus-navi
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: ai-secret
    creationPolicy: Owner

  data:
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: campus-navi-database-secret-json
        property: OPENAI_API_KEY